site_name: Truong Cong Dat Dodero
site_url: https://dodero.github.io/docs/
theme:
  name: material
  font: 
    text: Merriweather Sans
    code: Red Hat Mono

  logo: assets/logo.png
  favicon: assets/favicon_io/favicon.ico
  features:
    - navigation.footer
  palette:
    # Dark mode
    - scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to light mode
      primary: green
      accent: deep purple
    # Light mode
    - scheme: default
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
      primary: green
      accent: deep purple

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.mark
  - pymdownx.snippets
  - pymdownx.inlinehilite
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/dodero10
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/dodero/
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/dat.130503

copyright: Copyright &copy; 2024 Truong Cong Dat Dodero.
    



