site_name: Truong Cong Dat Dodero
site_url: https://dodero10.github.io/dodero/
theme:
  name: material
  font:
    text: Roboto
    code: Roboto Mono

  logo: assets/logo.png
  favicon: assets/favicon_io/favicon.ico
  features:
    - navigation.footer
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.indexes
    - navigation.top
    - navigation.tracking
    - navigation.instant
    - navigation.path
    - navigation.prune
    - toc.follow
    - navigation.tabs.sticky
  palette:
    # Dark mode
    - scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to light mode
      primary: green
      accent: deep purple
    # Light mode
    - scheme: default
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
      primary: green
      accent: deep purple

# Navigation structure
nav:
  - Home: index.md
  - About: about.md
  - Projects:
    - Overview: projects/index.md
    - Project 1: projects/project1.md
    - Dự Án 2: projects/project2.md
    
  - Blog:
    - blog/index.md
  - Math Examples: math-example.md
  - Contact: contact.md

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.mark
  - pymdownx.snippets
  - pymdownx.inlinehilite
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
  - pymdownx.arithmatex:
      generic: true

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/dodero10
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/dodero/
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/dat.130503

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

copyright: Copyright &copy; 2024 Truong Cong Dat Dodero.
    



